-- =============================================================
-- Foldermonitor — migratie (docs/foldermonitor-plan.md §6)
-- Idempotent. Draait in het PREVIEW-project tijdens de bouw en pas bij
-- de go-live (plan §9.5) in het productieproject. De tabel retailers
-- wordt aangemaakt als hij nog niet bestaat, zodat het preview-project
-- zelfstandig werkt; in productie is dat een no-op.
-- =============================================================

create table if not exists retailers (
  id        text primary key,
  name      text not null,
  website   text,
  segment   text,
  enabled   boolean not null default true
);

-- ---------- Folders (het origineel + herkomst) ----------
create table if not exists folders (
  id              bigint generated by default as identity primary key,
  retailer_id     text not null references retailers(id),
  source          text not null check (source in ('mail','web','upload')),
  title           text,
  valid_from      date,
  valid_to        date,
  received_at     timestamptz not null default now(),
  mail_message_id text,                   -- herkomst: Message-ID van de nieuwsbrief
  mail_subject    text,
  viewer_url      text,                   -- de online folder (Publitas/iPaper/eigen viewer)
  viewer_kind     text,                   -- pdf | publitas | ipaper | extern | pages | render | upload
  pdf_path        text,                   -- storage: folders/<retailer>/<jaar>/<id>.pdf
  page_count      int,
  sha256          text unique,            -- dedupe: zelfde folder via mail én web = één record
  status          text not null default 'nieuw'
                  check (status in ('nieuw','gearchiveerd','verwerkt','controle','fout')),
  note            text
);
create index if not exists idx_folders_retailer_geldig on folders (retailer_id, valid_from, valid_to);
create index if not exists idx_folders_status on folders (status);

-- ---------- Pagina's (werkformaat + classificatie) ----------
create table if not exists folder_pages (
  folder_id     bigint not null references folders(id) on delete cascade,
  page_no       int not null,
  image_path    text,                     -- storage: folders/<retailer>/<jaar>/<id>/p<nn>.webp
  theme         text,                     -- bodywear | kleding | huis | speelgoed | food | overig
  has_bodywear  boolean,
  is_hero       boolean not null default false,
  text_layer    text,                     -- tekst uit de PDF, als die er is
  primary key (folder_id, page_no)
);

-- ---------- Aanbiedingen (de data) ----------
create table if not exists folder_offers (
  id               bigint generated by default as identity primary key,
  folder_id        bigint not null references folders(id) on delete cascade,
  retailer_id      text not null references retailers(id),
  page_no          int,
  title            text not null,
  brand            text,
  audience         text not null default 'onbekend',
  product_type     text not null default 'overig',
  pack_size        int not null default 1,
  sizes            text,
  price            numeric(10,2),
  was_price        numeric(10,2),
  promo_text       text,                  -- ruwe actietekst ('2 voor € 7,50')
  promo_type       text not null default 'geen'
                   check (promo_type in ('geen','afprijzing','bundel','gratis_erbij',
                                         'tweede_halve_prijs','percentage')),
  effective_price  numeric(10,2),         -- effectieve prijs per stuk bij minimale afname
  is_hero          boolean not null default false,
  confidence       numeric(4,3),
  extraction       text,                  -- textlayer | vision | manual
  product_key      text,                  -- koppeling naar products (fase 3)
  match_confidence numeric(4,3),
  reviewed         boolean not null default false,
  created_at       timestamptz not null default now()
);
create index if not exists idx_folder_offers_folder on folder_offers (folder_id);
create index if not exists idx_folder_offers_groep on folder_offers (retailer_id, audience, product_type);

-- ---------- Weekaggregaten (zelfde sleutel als weekly_stats) ----------
create table if not exists folder_weekly_stats (
  retailer_id       text not null,
  week              date not null,         -- maandag van de week
  audience          text not null,
  product_type      text not null,
  offer_count       int not null default 0,
  hero_count        int not null default 0,
  price_min         numeric(10,2),
  price_median      numeric(10,2),
  unit_price_median numeric(10,2),
  multibuy_share    numeric(6,4),
  discount_share    numeric(6,4),
  primary key (retailer_id, week, audience, product_type)
);
create index if not exists idx_folder_weekly_stats_week on folder_weekly_stats (week);

-- ---------- Gezondheid per stap (zoals scrape_runs) ----------
create table if not exists folder_runs (
  id          bigint generated by default as identity primary key,
  retailer_id text,
  week        date,
  run_at      timestamptz not null default now(),
  step        text not null,              -- sweep | capture | classify | extract | process
  status      text not null,              -- ok | afwijkend | fout
  note        text
);
create index if not exists idx_folder_runs_week on folder_runs (week);

-- ---------- Verwerkingsfunctie ----------
-- Weekregel (plan §6): een folder telt mee in elke week waarin hij op de
-- maandag (peildatum) geldig is. Idempotent per (bron, week).
create or replace function process_folder_week(p_retailer text, p_week date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_folders int; v_groups int;
begin
  delete from folder_weekly_stats where retailer_id = p_retailer and week = p_week;

  insert into folder_weekly_stats (retailer_id, week, audience, product_type,
    offer_count, hero_count, price_min, price_median, unit_price_median,
    multibuy_share, discount_share)
  select p_retailer, p_week, o.audience, o.product_type,
         count(*)::int,
         (count(*) filter (where o.is_hero))::int,
         min(o.price),
         percentile_cont(0.5) within group (order by o.price),
         round((percentile_cont(0.5) within group
                 (order by o.price / greatest(coalesce(o.pack_size, 1), 1)))::numeric, 2),
         round(avg(case when o.promo_type in ('bundel','gratis_erbij','tweede_halve_prijs')
                        then 1 else 0 end)::numeric, 4),
         round(avg(case when o.promo_type in ('afprijzing','percentage')
                          or (o.was_price is not null and o.price is not null and o.was_price > o.price)
                        then 1 else 0 end)::numeric, 4)
  from folder_offers o
  join folders f on f.id = o.folder_id
  where f.retailer_id = p_retailer and f.status = 'verwerkt'
    and f.valid_from <= p_week and f.valid_to >= p_week
  group by o.audience, o.product_type;
  get diagnostics v_groups = row_count;

  select count(*) into v_folders from folders f
  where f.retailer_id = p_retailer and f.status = 'verwerkt'
    and f.valid_from <= p_week and f.valid_to >= p_week;

  return jsonb_build_object('folders', v_folders, 'groups', v_groups);
end;
$$;
revoke execute on function process_folder_week(text, date) from public, anon, authenticated;

-- ---------- Nederlandstalige views ----------
drop view if exists v_folders;
create view v_folders with (security_invoker = true) as
  select f.id,
         f.retailer_id            as bron,
         r.name                   as bronnaam,
         f.valid_from             as geldig_van,
         f.valid_to               as geldig_tot,
         f.received_at            as ontvangen,
         f.source                 as herkomst,
         f.viewer_kind            as viewer,
         f.page_count             as paginas,
         (select count(*) from folder_pages p where p.folder_id = f.id and p.has_bodywear) as bodywear_paginas,
         (select count(*) from folder_offers o where o.folder_id = f.id) as aanbiedingen,
         f.status,
         f.pdf_path,
         f.viewer_url,
         f.title                  as titel
  from folders f
  join retailers r on r.id = f.retailer_id;

drop view if exists v_folder_aanbiedingen;
create view v_folder_aanbiedingen with (security_invoker = true) as
  select o.id,
         o.retailer_id            as bron,
         f.valid_from             as geldig_van,
         f.valid_to               as geldig_tot,
         o.folder_id,
         o.page_no                as pagina,
         o.title                  as artnaam,
         o.brand                  as merk,
         o.audience               as hoofdcategorie,
         o.product_type           as categorie,
         o.pack_size              as stuks_per_verpakking,
         o.sizes                  as maten,
         o.was_price              as van_prijs,
         o.price                  as voor_prijs,
         round(o.price / greatest(coalesce(o.pack_size, 1), 1), 2) as prijs_per_stuk,
         o.promo_text             as actie,
         o.promo_type             as actietype,
         o.effective_price        as effectieve_stukprijs,
         o.is_hero                as hero,
         o.confidence             as betrouwbaarheid,
         o.extraction             as extractie,
         o.product_key            as online_artnr,
         o.match_confidence       as koppelzekerheid,
         o.reviewed               as gecontroleerd
  from folder_offers o
  join folders f on f.id = o.folder_id;

-- Retailkalender: bron × week (maandag) waarin een folder geldig is.
drop view if exists v_retailkalender;
create view v_retailkalender with (security_invoker = true) as
  select f.retailer_id as bron,
         w.week,
         count(distinct f.id)::int                                        as folders,
         coalesce(sum(f.page_count), 0)::int                              as paginas,
         (select count(*) from folder_pages p
           where p.folder_id = any(array_agg(f.id)) and p.has_bodywear)::int as bodywear_paginas,
         (select count(*) from folder_offers o
           where o.folder_id = any(array_agg(f.id)))::int                 as aanbiedingen,
         bool_or(f.status = 'verwerkt')                                    as verwerkt
  from folders f
  cross join lateral (
    select d::date as week
    from generate_series(date_trunc('week', f.valid_from)::timestamp,
                         f.valid_to::timestamp, interval '1 week') d
  ) w
  where f.valid_from is not null and f.valid_to is not null
    and w.week between f.valid_from and f.valid_to
  group by f.retailer_id, w.week;

-- ---------- Toegangsbeleid ----------
alter table retailers           enable row level security;
alter table folders             enable row level security;
alter table folder_pages        enable row level security;
alter table folder_offers       enable row level security;
alter table folder_weekly_stats enable row level security;
alter table folder_runs         enable row level security;

drop policy if exists lezen_ingelogd on retailers;
create policy lezen_ingelogd on retailers           for select to authenticated using (true);
drop policy if exists lezen_ingelogd on folders;
create policy lezen_ingelogd on folders             for select to authenticated using (true);
drop policy if exists lezen_ingelogd on folder_pages;
create policy lezen_ingelogd on folder_pages        for select to authenticated using (true);
drop policy if exists lezen_ingelogd on folder_offers;
create policy lezen_ingelogd on folder_offers       for select to authenticated using (true);
drop policy if exists lezen_ingelogd on folder_weekly_stats;
create policy lezen_ingelogd on folder_weekly_stats for select to authenticated using (true);
drop policy if exists lezen_ingelogd on folder_runs;
create policy lezen_ingelogd on folder_runs         for select to authenticated using (true);

-- Controlelijst: ingelogde gebruikers mogen alleen 'reviewed' afvinken.
revoke update on folder_offers from authenticated;
grant update (reviewed) on folder_offers to authenticated;
drop policy if exists controle_ingelogd on folder_offers;
create policy controle_ingelogd on folder_offers for update to authenticated
  using (true) with check (true);

-- ---------- Storage: buckets en policies ----------
-- 'folders': PDF's en paginabeelden (schrijven: service-rol).
-- 'folders-inbox': handmatige upload van PDF's door ingelogde gebruikers.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('folders', 'folders', false, 52428800, null)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('folders-inbox', 'folders-inbox', false, 52428800, array['application/pdf'])
on conflict (id) do nothing;

drop policy if exists folders_lezen_ingelogd on storage.objects;
create policy folders_lezen_ingelogd on storage.objects for select to authenticated
  using (bucket_id in ('folders', 'folders-inbox'));
drop policy if exists folders_inbox_upload_ingelogd on storage.objects;
create policy folders_inbox_upload_ingelogd on storage.objects for insert to authenticated
  with check (bucket_id = 'folders-inbox');
