-- =============================================================
-- Concurrentiemonitor terStal — Supabase/Postgres schema
-- Eén keer uitvoeren in de Supabase SQL-editor (Dashboard > SQL).
-- Idempotent: kan veilig opnieuw worden uitgevoerd.
-- =============================================================

-- ---------- Tabellen ----------

create table if not exists retailers (
  id        text primary key,          -- bv. 'zeeman'
  name      text not null,
  website   text,
  segment   text,                      -- 'kern' | 'breed' | 'referentie'
  enabled   boolean not null default true
);

create table if not exists products (
  retailer_id       text not null references retailers(id),
  product_key       text not null,     -- stabiele sleutel: SKU/id of URL-hash
  url               text,
  title             text,
  brand             text,
  category_raw      text,              -- oorspronkelijk categoriepad van de bron
  audience          text not null default 'onbekend',
  product_type      text not null default 'overig',
  color             text,              -- kleur(en), best effort per bron
  sizes             text,              -- aangeboden maten, bv. "92, 104, 116" (geen voorraad!)
  first_seen        date not null,     -- maandag van de week van eerste waarneming
  last_seen         date not null,
  status            text not null default 'active' check (status in ('active','gone')),
  current_price     numeric(10,2),
  current_was_price numeric(10,2),
  primary key (retailer_id, product_key)
);
create index if not exists idx_products_status on products (retailer_id, status);

-- Alleen mutaties, geen wekelijkse snapshots: houdt de database klein.
create table if not exists price_events (
  id          bigint generated by default as identity primary key,
  retailer_id text not null,
  product_key text not null,
  week        date not null,           -- maandag van de waarnemingsweek
  event       text not null check (event in
              ('new','back','price_up','price_down','promo_start','promo_end','gone')),
  price       numeric(10,2),
  was_price   numeric(10,2),
  prev_price  numeric(10,2),
  created_at  timestamptz not null default now(),
  -- deferred: 'new'-events worden vóór de products-upsert geschreven,
  -- binnen dezelfde transactie klopt de verwijzing bij commit alsnog
  foreign key (retailer_id, product_key) references products (retailer_id, product_key)
    deferrable initially deferred
);
create index if not exists idx_events_week on price_events (week, retailer_id);

-- Kant-en-klare weekaggregaten: het dashboard leest vrijwel alleen deze tabel.
create table if not exists weekly_stats (
  retailer_id      text not null,
  week             date not null,
  audience         text not null,
  product_type     text not null,
  active_count     int  not null default 0,
  new_count        int  not null default 0,
  gone_count       int  not null default 0,
  price_min        numeric(10,2),
  price_p25        numeric(10,2),
  price_median     numeric(10,2),
  price_p75        numeric(10,2),
  price_p90        numeric(10,2),
  price_avg        numeric(10,2),
  sale_share       numeric(6,4),       -- aandeel artikelen met doorstreepte prijs (0..1)
  avg_discount_pct numeric(6,1),       -- gem. kortingsdiepte in % (alleen sale-artikelen)
  primary key (retailer_id, week, audience, product_type)
);
create index if not exists idx_weekly_stats_week on weekly_stats (week);

-- De wekelijkse artikelfoto: per artikel per week één regel (artnr t/m URL).
-- Groei binnen de ondergoedfocus: ±2.500 rijen/week ≈ 35 MB/jaar — past ruim.
-- Bij verbreding naar het volledige assortiment: bewaartermijn instellen, bv.
--   delete from weekly_articles where week < current_date - interval '26 weeks';
create table if not exists weekly_articles (
  retailer_id  text not null,
  week         date not null,
  product_key  text not null,
  title        text,
  audience     text,                   -- hoofdcategorie (doelgroep)
  product_type text,                   -- categorie (uniform producttype)
  category_raw text,                   -- categoriepad zoals de bron het noemt
  color        text,
  sizes        text,
  price        numeric(10,2),          -- voor-prijs
  was_price    numeric(10,2),          -- van-prijs (leeg = geen aanbieding)
  url          text,
  primary key (retailer_id, week, product_key)
);
create index if not exists idx_weekly_articles_week on weekly_articles (week);

-- Gezondheid van elke scrape-run (voedt de rode/groene tabel in het weekrapport).
create table if not exists scrape_runs (
  id             bigint generated by default as identity primary key,
  retailer_id    text not null,
  week           date not null,
  run_at         timestamptz not null default now(),
  strategy       text,
  products_found int,
  status         text not null,        -- 'ok' | 'afwijkend' | 'fout'
  note           text
);
create index if not exists idx_runs_week on scrape_runs (week);

-- Tussentabel: de scraper zet hier de weeksnapshot in; process_staging verwerkt set-based.
create table if not exists staging_products (
  retailer_id  text not null,
  product_key  text not null,
  url          text,
  title        text,
  brand        text,
  category_raw text,
  audience     text not null default 'onbekend',
  product_type text not null default 'overig',
  color        text,
  sizes        text,
  price        numeric(10,2),
  was_price    numeric(10,2)
);
create index if not exists idx_staging_retailer on staging_products (retailer_id);

-- ---------- Verwerkingsfunctie (het rekenhart) ----------
-- Vergelijkt de staging-snapshot met de bekende stand, schrijft events,
-- werkt products bij en berekent weekly_stats — alles set-based in één transactie.

create or replace function process_staging(p_retailer text, p_week date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total int; v_new int; v_back int; v_up int; v_down int;
  v_promo_start int; v_promo_end int; v_gone int;
begin
  create temp table _snap on commit drop as
    select distinct on (product_key) *
    from staging_products
    where retailer_id = p_retailer;

  select count(*) into v_total from _snap;
  if v_total = 0 then
    raise exception 'staging is leeg voor % — verwerking afgebroken', p_retailer;
  end if;

  -- Nieuw: nooit eerder gezien.
  insert into price_events (retailer_id, product_key, week, event, price, was_price)
  select s.retailer_id, s.product_key, p_week, 'new', s.price, s.was_price
  from _snap s
  left join products p on p.retailer_id = s.retailer_id and p.product_key = s.product_key
  where p.product_key is null;
  get diagnostics v_new = row_count;

  -- Terug: was verdwenen, duikt weer op.
  insert into price_events (retailer_id, product_key, week, event, price, was_price)
  select s.retailer_id, s.product_key, p_week, 'back', s.price, s.was_price
  from _snap s
  join products p on p.retailer_id = s.retailer_id and p.product_key = s.product_key
  where p.status = 'gone';
  get diagnostics v_back = row_count;

  -- Prijsverhoging / -verlaging op bestaande actieve artikelen.
  insert into price_events (retailer_id, product_key, week, event, price, was_price, prev_price)
  select s.retailer_id, s.product_key, p_week, 'price_up', s.price, s.was_price, p.current_price
  from _snap s
  join products p on p.retailer_id = s.retailer_id and p.product_key = s.product_key
  where p.status = 'active' and s.price is not null and p.current_price is not null
    and s.price > p.current_price;
  get diagnostics v_up = row_count;

  insert into price_events (retailer_id, product_key, week, event, price, was_price, prev_price)
  select s.retailer_id, s.product_key, p_week, 'price_down', s.price, s.was_price, p.current_price
  from _snap s
  join products p on p.retailer_id = s.retailer_id and p.product_key = s.product_key
  where p.status = 'active' and s.price is not null and p.current_price is not null
    and s.price < p.current_price;
  get diagnostics v_down = row_count;

  -- Promotie gestart / beëindigd (doorstreepte prijs verschijnt/verdwijnt).
  insert into price_events (retailer_id, product_key, week, event, price, was_price, prev_price)
  select s.retailer_id, s.product_key, p_week, 'promo_start', s.price, s.was_price, p.current_price
  from _snap s
  join products p on p.retailer_id = s.retailer_id and p.product_key = s.product_key
  where p.status = 'active'
    and (s.was_price is not null and s.price is not null and s.was_price > s.price)
    and not (p.current_was_price is not null and p.current_price is not null
             and p.current_was_price > p.current_price);
  get diagnostics v_promo_start = row_count;

  insert into price_events (retailer_id, product_key, week, event, price, was_price, prev_price)
  select s.retailer_id, s.product_key, p_week, 'promo_end', s.price, s.was_price, p.current_price
  from _snap s
  join products p on p.retailer_id = s.retailer_id and p.product_key = s.product_key
  where p.status = 'active'
    and not (s.was_price is not null and s.price is not null and s.was_price > s.price)
    and (p.current_was_price is not null and p.current_price is not null
         and p.current_was_price > p.current_price);
  get diagnostics v_promo_end = row_count;

  -- Actuele stand bijwerken.
  insert into products (retailer_id, product_key, url, title, brand, category_raw,
                        audience, product_type, color, sizes, first_seen, last_seen,
                        status, current_price, current_was_price)
  select s.retailer_id, s.product_key, s.url, s.title, s.brand, s.category_raw,
         s.audience, s.product_type, s.color, s.sizes, p_week, p_week, 'active',
         s.price, s.was_price
  from _snap s
  on conflict (retailer_id, product_key) do update set
    url = excluded.url,
    title = excluded.title,
    brand = excluded.brand,
    category_raw = excluded.category_raw,
    audience = excluded.audience,
    product_type = excluded.product_type,
    last_seen = excluded.last_seen,
    status = 'active',
    color = excluded.color,
    sizes = excluded.sizes,
    current_price = excluded.current_price,
    current_was_price = excluded.current_was_price;

  -- Wekelijkse artikelfoto (artnr t/m URL) — idempotent per (bron, week).
  delete from weekly_articles where retailer_id = p_retailer and week = p_week;
  insert into weekly_articles (retailer_id, week, product_key, title, audience,
    product_type, category_raw, color, sizes, price, was_price, url)
  select s.retailer_id, p_week, s.product_key, s.title, s.audience,
         s.product_type, s.category_raw, s.color, s.sizes, s.price, s.was_price, s.url
  from _snap s;

  -- Verdwenen: actief maar niet in deze snapshot. Op de snapshot toetsen, niet
  -- op last_seen < p_week: een herdraai binnen dezelfde week liet anders de
  -- rijen van de eerdere poging actief staan (Action, week 32: 27 banners
  -- bleven naast de 24 echte artikelen staan en vervuilden elke poort erna).
  insert into price_events (retailer_id, product_key, week, event, prev_price)
  select p.retailer_id, p.product_key, p_week, 'gone', p.current_price
  from products p
  where p.retailer_id = p_retailer and p.status = 'active'
    and not exists (select 1 from _snap s where s.product_key = p.product_key);
  get diagnostics v_gone = row_count;

  update products p set status = 'gone'
  where p.retailer_id = p_retailer and p.status = 'active'
    and not exists (select 1 from _snap s where s.product_key = p.product_key);

  -- Weekaggregaten (huidige actieve stand + uitstroom van deze week).
  delete from weekly_stats where retailer_id = p_retailer and week = p_week;

  insert into weekly_stats (retailer_id, week, audience, product_type,
    active_count, new_count, gone_count,
    price_min, price_p25, price_median, price_p75, price_p90, price_avg,
    sale_share, avg_discount_pct)
  with snap as (
    select audience, product_type, current_price as price, current_was_price as was_price, first_seen
    from products
    where retailer_id = p_retailer and status = 'active'
  ), snap_g as (
    select audience, product_type,
      count(*)::int as active_count,
      (count(*) filter (where first_seen = p_week))::int as new_count,
      min(price) as price_min,
      percentile_cont(0.25) within group (order by price) as price_p25,
      percentile_cont(0.50) within group (order by price) as price_median,
      percentile_cont(0.75) within group (order by price) as price_p75,
      percentile_cont(0.90) within group (order by price) as price_p90,
      round(avg(price), 2) as price_avg,
      round(avg(case when was_price is not null and price is not null and was_price > price
                     then 1 else 0 end)::numeric, 4) as sale_share,
      round(avg(case when was_price is not null and price is not null and was_price > price
                     then (was_price - price) / was_price * 100 end)::numeric, 1) as avg_discount_pct
    from snap
    group by 1, 2
  ), gone_g as (
    select p.audience, p.product_type, count(*)::int as gone_count
    from price_events e
    join products p on p.retailer_id = e.retailer_id and p.product_key = e.product_key
    where e.retailer_id = p_retailer and e.week = p_week and e.event = 'gone'
    group by 1, 2
  )
  select p_retailer, p_week,
         coalesce(sg.audience, gg.audience),
         coalesce(sg.product_type, gg.product_type),
         coalesce(sg.active_count, 0),
         coalesce(sg.new_count, 0),
         coalesce(gg.gone_count, 0),
         sg.price_min, sg.price_p25, sg.price_median, sg.price_p75, sg.price_p90,
         sg.price_avg, sg.sale_share, sg.avg_discount_pct
  from snap_g sg
  full join gone_g gg using (audience, product_type);

  delete from staging_products where retailer_id = p_retailer;

  return jsonb_build_object(
    'products', v_total, 'new', v_new, 'back', v_back,
    'price_up', v_up, 'price_down', v_down,
    'promo_start', v_promo_start, 'promo_end', v_promo_end, 'gone', v_gone);
end;
$$;

-- Alleen de service-rol (de wekelijkse job) mag verwerken.
revoke execute on function process_staging(text, date) from public, anon, authenticated;

-- ---------- Hulpviews voor het dashboard ----------

create or replace view v_weeks with (security_invoker = true) as
  select distinct week from weekly_stats order by week desc;

create or replace view v_retailer_week_totals with (security_invoker = true) as
  select retailer_id, week,
         sum(active_count)::int as active_count,
         sum(new_count)::int    as new_count,
         sum(gone_count)::int   as gone_count,
         round(sum(sale_share * active_count) / nullif(sum(active_count), 0), 4) as sale_share
  from weekly_stats
  group by retailer_id, week;

-- Nederlandstalige exportview: per artikel per week, kolomnamen volgens de
-- business. CSV-export kan direct vanuit de Supabase Table Editor / SQL-editor.
create or replace view v_artikelen_week with (security_invoker = true) as
  select a.retailer_id  as bron,
         a.week,
         a.product_key  as artnr,
         a.title        as artnaam,
         a.audience     as hoofdcategorie,
         a.product_type as categorie,
         a.category_raw as bron_categorie,
         a.color        as kleur,
         a.sizes        as maten,
         a.was_price    as van_prijs,
         a.price        as voor_prijs,
         a.url
  from weekly_articles a;

-- ---------- Toegangsbeleid ----------
-- Lezen: alleen ingelogde dashboardgebruikers (magic link via Supabase Auth).
-- Schrijven: uitsluitend de service-rol van de wekelijkse job (omzeilt RLS).
-- staging_products krijgt bewust géén leesbeleid: onzichtbaar voor clients.

alter table retailers        enable row level security;
alter table products         enable row level security;
alter table price_events     enable row level security;
alter table weekly_stats     enable row level security;
alter table weekly_articles  enable row level security;
alter table scrape_runs      enable row level security;
alter table staging_products enable row level security;

drop policy if exists lezen_ingelogd on retailers;
create policy lezen_ingelogd on retailers    for select to authenticated using (true);
drop policy if exists lezen_ingelogd on products;
create policy lezen_ingelogd on products     for select to authenticated using (true);
drop policy if exists lezen_ingelogd on price_events;
create policy lezen_ingelogd on price_events for select to authenticated using (true);
drop policy if exists lezen_ingelogd on weekly_stats;
create policy lezen_ingelogd on weekly_stats for select to authenticated using (true);
drop policy if exists lezen_ingelogd on weekly_articles;
create policy lezen_ingelogd on weekly_articles for select to authenticated using (true);
drop policy if exists lezen_ingelogd on scrape_runs;
create policy lezen_ingelogd on scrape_runs  for select to authenticated using (true);
